version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules:
